services:
  web:
    build: 
      context: ../../
      dockerfile: .docker/production/Dockerfile
    container_name: documentations_web
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true